/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
	Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : MainPage.xaml.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : 
*/

#pragma once

#include "MainPage.g.h"
#include "FrameWork\Timer.h"
#include "Scenes\SimpleScene.h"

using namespace Windows::UI::Core;

namespace Chapter5
{
	/// <summary>
	/// An empty page that can be used on its own or navigated to within a Frame.
	/// </summary>
	public ref class MainPage sealed
	{
	private:
		bool isDisposed;
		bool isWindowVisible;
		Timer^ timer;
		Windows::Foundation::EventRegistrationToken  renderingEventToken;
		SimpleScene^ Scene;
	public:
		MainPage();

	protected:
		virtual void OnNavigatedTo(Windows::UI::Xaml::Navigation::NavigationEventArgs^ e) override;
	private:
		void OnDisplayContentsInvalidated(Object^ sender);
		void OnLoaded(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
		void OnUnloaded(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
		void OnRendering(Platform::Object^ sender, Platform::Object^ args);
		void OnVisibilityChanged(CoreWindow^ sender, VisibilityChangedEventArgs^ args);
		void OnSizeChanged(CoreWindow^ sender, WindowSizeChangedEventArgs^ e);
		void OnKeyDown(CoreWindow^ sender, KeyEventArgs^ args);
		void OnKeyUp(CoreWindow^ sender, KeyEventArgs^ args);
		void OnPointerPressed(CoreWindow^ sender, PointerEventArgs^ args);
		void OnPointerReleased(CoreWindow^ sender, PointerEventArgs^ args);
		void OnPointerMoved(CoreWindow^ sender, PointerEventArgs^ args);
		void OnExitBtnClicked(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
		void OnWireChecked(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
		void OnSolidChecked(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
	};
}
