/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/ 
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
    Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : SpriteBatch.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : This class used for handling Direct2D functions
 */

#pragma once

#include "Fonts/SpriteFont.h"
#include <DirectXMath.h>

using namespace Platform;
using namespace Microsoft::WRL;
using namespace DirectX;

ref class SpriteBatch
{
internal:
	SpriteBatch();
	void SetBackgroundColor(ColorF BackColor, ColorF BorderColor);
	void Begin();
	void ShowRectangle();
	HRESULT ShowString(String^ text, const XMFLOAT2* position, SpriteFont^ spriteFont);
	HRESULT ShowString(String^ text, const XMFLOAT2* position, ID2D1SolidColorBrush* brush, SpriteFont^ spriteFont, Matrix3x2F World);
	HRESULT End();

private:
	String^ text;
	enum SpriteState : byte { STARTED, ENDED };
	SpriteState state;
	D2D1_RECT_F BackgroundText;
	ComPtr<ID2D1SolidColorBrush> BackgroundBrush;
	ComPtr<ID2D1SolidColorBrush> BackgroundBorder;
	ComPtr<IDWriteTextLayout> textLayout;
	ComPtr<ID2D1DrawingStateBlock1> stateBlock;
};