/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/ 
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
    Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : SpriteBatch.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : The declaration of vertex types
 */

#pragma once

#include <wrl/client.h>
#include <DirectXMath.h>

using namespace DirectX;

enum VertexDeclaration : byte
{
	NOP,
	Position,
	PositionColor,
	PositionNormalColor,
	PositionTexture,
	PositionNormalTexture,
	PositionNormalTextureTangent,
	PositionNormalTextureTangentBinormal,
	PositionNormalTangentColorTexture
};

namespace VertexTypes
{
	struct VertexPosition
	{
		XMFLOAT3 Position;
	};

	struct VertexPositionColor
	{
		XMFLOAT3 Position;
		XMFLOAT4 Color;
	};

	struct VertexPositionNormalColor
	{
		XMFLOAT3 Position;
		XMFLOAT3 Normal;
		XMFLOAT4 Color;
	};
	
	struct VertexPositionTexture
	{
		XMFLOAT3 Position;
		XMFLOAT2 TexCoord;
	};

	struct VertexPositionNormalTexture
	{
		XMFLOAT3 Position;
		XMFLOAT3 Normal;
		XMFLOAT2 TexCoord;
	}; 

	struct VertexPositionNormalTextureTangent
	{
		XMFLOAT3 Position;
		XMFLOAT3 Normal;
		XMFLOAT2 Texcoord;
		XMFLOAT3 Tangent;
	};

	struct VertexPositionNormalTextureTangentBinormal
	{
		XMFLOAT3 Position;
		XMFLOAT3 Normal;
		XMFLOAT2 Texcoord;
		XMFLOAT3 Tangent;
		XMFLOAT3 Binormal;
	};

	struct VertexPositionNormalTangentColorTexture
	{
		XMFLOAT3 Position;
		XMFLOAT3 Normal;
		XMFLOAT4 Tangent;
		UINT     Color;
		XMFLOAT2 TexCoord;
	};
}