/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/ 
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
    Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : FPS.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : Display the frame per second
 */
#pragma once

using namespace Microsoft::WRL;

ref class FPS
{
internal:
	FPS();
	void Update(float ElapsedTime);
	void Render();

	property ID2D1SolidColorBrush* FpsColor
	{
		ID2D1SolidColorBrush* get()
		{
			if (this->state == State::Normal)
			{
				return this->LimeSolidBrushColor.Get();
			}
			if (this->state == State::Warning)
			{
				return this->YellowSolidBrushColor.Get();
			}
			return this->RedSolidBrushColor.Get();
		}
	}	
	property float fps
	{
		float get()
		{
			return this->_fps;
		}
	}

private:
	float _fps;
	float elapsedTime;
	UINT frames;
	enum State { Normal, Warning, Error } state;
	ComPtr<ID2D1SolidColorBrush> RedSolidBrushColor;
	ComPtr<ID2D1SolidColorBrush> YellowSolidBrushColor;
	ComPtr<ID2D1SolidColorBrush> LimeSolidBrushColor;
};