/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/ 
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
    Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : Perf.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : 
 */
#pragma once

#include "Graphics\SpriteBatch.h"
#include "FPS.h"
#include "CpuInfo.h"

ref class Perf
{
internal:
	Perf();
	void ShowStatus(SpriteBatch^ spriteBatch, SpriteFont^ spriteFont, DirectX::XMFLOAT2* Position);
private:
	float totalTime, deltaTime;
	FPS^ _FPS;
	CpuInfo^ _CPU;
public:
	void Update(float TotalTime, float DeltaTime);
};