/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
	Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : InputManager.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description :
*/

#pragma once

#include "Comps\KeyboardState.h"
#include "Comps\PointerState.h"
#include "Comps\GamePadState.h"

namespace InputManager
{
	extern KeyboardState keyboardState;
	extern PointerState  pointerState;
	extern GamePadState  gamePadState;

	extern void Update();
	extern void ClearBuffers();
	extern void Unload();
}
