/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/ 
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
    Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : SimpleScene.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : The main scene
 */

#pragma once

#include "FrameWork/Game.h"
#include "Graphics/SpriteBatch.h"
#include "FrameWork/System/Perf.h"
#include "Graphics/Models/ModelManager.h"

ref class SimpleScene sealed : public Game
{
private:

	int batchSize;
	std::vector<int> indices;
	bool loadingComplete;
	float BackColor[4];
	SpriteBatch^ spriteBatch;
	SpriteFont^ spriteFont;
	Perf^ perf;
	ModelManager^ modelManager; 
	String^ MSG;

public:
	SimpleScene();
	void InitializeThreads();
	void Load();
	void Unload();
	void Update(float TotalTime, float DeltaTime);
	virtual void Render() override;
}; 