/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/ 
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
    Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : Window.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : The main window
 */

#pragma once

#include "pch.h"
#include "SimpleScene.h"

using namespace Platform;
using namespace Windows::UI::Core;
using namespace Windows::ApplicationModel;
using namespace Windows::ApplicationModel::Core;
using namespace Windows::ApplicationModel::Activation;

ref class Window sealed : public IFrameworkView
{
private:
	bool isWindowClosed;
	bool isWindowVisible;
	SimpleScene^ Scene;

public:
	Window();

	// IFrameworkView Methods.
	virtual void Initialize(CoreApplicationView^ applicationView);
	virtual void SetWindow(CoreWindow^ window);
	virtual void Load(String^ entryPoint);
	virtual void Run();
	virtual void Uninitialize();

protected:
	// Event Handlers.
	void OnWindowSizeChanged(CoreWindow^ sender, WindowSizeChangedEventArgs^ args);
	void OnLogicalDpiChanged(Object^ sender);
	void OnActivated(CoreApplicationView^ appView, IActivatedEventArgs^ args);
	void OnSuspending(Object^ sender, SuspendingEventArgs^ args);
	void OnResuming(Object^ sender, Object^ args);
	void OnWindowClosed(CoreWindow^ sender, CoreWindowEventArgs^ args);
	void OnVisibilityChanged(CoreWindow^ sender, VisibilityChangedEventArgs^ args);
	void OnPointerPressed(CoreWindow^ sender, PointerEventArgs^ args);
	void OnPointerReleased(CoreWindow^ sender, PointerEventArgs^ args);
	void OnPointerMoved(CoreWindow^ sender, PointerEventArgs^ args);
	void OnKeyDown(CoreWindow^ sender, KeyEventArgs^ args);
	void OnKeyUp(CoreWindow^ sender, KeyEventArgs^ args);
};

ref class App sealed : IFrameworkViewSource
{
public:
	virtual IFrameworkView^ CreateView();
};

