/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
	Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : CPU.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description :
*/

#pragma once

#define GUID_DEVICE_PROCESSOR "{97FADB10-4E33-40AE-359C-8BEF029DBDD0}"

using namespace Platform;

ref class CPU
{
internal:
	CPU();
private:
	byte totalCores;
	String^ name;
public:
	property String^ Name
	{
		String^ get()
		{
			return this->name;
		}
	}
	property byte TotalCores
	{
		byte get()
		{
			return this->totalCores;
		}
	}
};

