/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
	Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : MediaEngine.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description :
*/

#pragma once

ref class MediaEngine
{
internal:
	MediaEngine();

	Platform::Array<byte>^ MediaEngine::LoadSound(Platform::String^ filename);
	void Load();
	void Suspend();
	void Resume();

	property IXAudio2* Engine
	{
		IXAudio2* get()
		{
			return this->m_soundEffectEngine.Get();
		}
	}
	property WAVEFORMATEX* Format
	{
		WAVEFORMATEX* get()
		{
			return &this->m_waveFormat;
		}
	}

private:
	bool                                m_audioAvailable;
	WAVEFORMATEX                        m_waveFormat;
	Microsoft::WRL::ComPtr<IXAudio2>    m_soundEffectEngine;
	IXAudio2MasteringVoice*             m_soundEffectMasteringVoice;
};

