/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
	Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : InputManager.cpp
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description :
*/

#include "pch.h"
#include "..\InputManager.h"

KeyboardState InputManager::keyboardState;
PointerState  InputManager::pointerState;
GamePadState  InputManager::gamePadState;

void InputManager::Update()
{
	gamePadState.Update();
}

void InputManager::ClearBuffers()
{
	keyboardState.ClearBuffer();
	gamePadState.ClearBuffers();
}

void InputManager::Unload()
{
	keyboardState.Unload();
	gamePadState.Unload();
}


