/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/ 
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
    Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : PointerState.cpp
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : 
 */
#include "pch.h"
#include "PointerState.h"

using namespace Windows::UI::Input;
using namespace Windows::Foundation;

PointerState::PointerState()
{
}

void PointerState::SavePosition( Point Position )
{
	this->position.x = Position.X;
	this->position.y = Position.Y;
}

void PointerState::SaveState( PointerPointProperties^ Properties )
{
	this->state = Properties;
}

bool PointerState::IsLeftButtonPressed()
{
	if(this->state == nullptr) return false;
	return this->state->IsLeftButtonPressed;
}

bool PointerState::IsRightButtonPressed()
{
	if(this->state == nullptr) return false;
	return this->state->IsRightButtonPressed;
}


