/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/ 
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
    Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : PointerState.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : Represent the state of pointer
 */
#pragma once

ref class PointerState
{
private:
	DirectX::XMFLOAT2 position;
	Windows::UI::Input::PointerPointProperties^ state;
internal:
	PointerState();

	void SavePosition(Windows::Foundation::Point Position);
	void SaveState( Windows::UI::Input::PointerPointProperties^ Properties );
	bool IsLeftButtonPressed();
	bool IsRightButtonPressed();

	property DirectX::XMFLOAT2 Position
	{
		DirectX::XMFLOAT2 get()
		{
			return this->position;
		}
	}
};