/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/ 
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
    Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : SpriteFont.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : Declare the font style
 */
#pragma once

#include <wrl/client.h>
#include <d2d1_1.h>
#include <dwrite_1.h>

using namespace D2D1;
using namespace Microsoft::WRL;

struct SpriteFontStyle
{
	DWRITE_FONT_WEIGHT WEIGHT;
	DWRITE_FONT_STYLE  STYLE;
	DWRITE_FONT_STRETCH STRETCH;
	DWRITE_TEXT_ALIGNMENT TEXT_ALIGNMENT;
	DWRITE_PARAGRAPH_ALIGNMENT PARAGRAPH_ALIGNMENT;
	float SIZE;
	const WCHAR* LOCAL;
};

ref class SpriteFont
{
internal:
	SpriteFont();
	HRESULT Load();
	HRESULT SetColor(ColorF color);
	property IDWriteTextFormat* Font
	{
		IDWriteTextFormat* get()
		{
			return this->font.Get();
		}
	}
	property ID2D1SolidColorBrush* Brush
	{
		ID2D1SolidColorBrush* get()
		{
			return this->brush.Get();
		}
	}

private:
	SpriteFontStyle fontStyle;
	ComPtr<ID2D1SolidColorBrush> brush; 
	ComPtr<IDWriteTextFormat> font;
	ComPtr<IDWriteTextLayout> textLayout;
};
