/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/ 
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
    Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : Game.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description : The base class for the game
 */
#pragma once

#include <wrl.h>
#include <agile.h>
#include <d2d1_1.h>
#include <dwrite_1.h>
#include <d3d11_1.h>

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::UI::Core;

ref class Game abstract
{
internal:
	//Constructor 
	Game();

private:
	void CreateDevice();
	void CreateWindowSize();
	void HandleDeviceLost();
	void LoadDefaultVertexShader();

protected private:
	//D3D Objects
	ComPtr<IDXGISwapChain1> swapChain;
	ComPtr<ID3D11RenderTargetView> renderTargetView;
	ComPtr<ID3D11DepthStencilView> depthStencilView;

	D3D_FEATURE_LEVEL featureLevel;
	Windows::Foundation::Size renderTargetSize;
	Windows::Foundation::Rect windowBounds;
	Agile<CoreWindow> coreWindow;

public:
	virtual void Initialize(CoreWindow^ window);
	virtual void WindowSizeChanged();
	virtual void Render() = 0;
	virtual void Present();
};
