/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
	Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : KeyboardState.cpp
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description :
*/

#include "pch.h"
#include "..\KeyboardState.h"

using namespace Windows::System;

KeyboardState::KeyboardState()
{
}

KeyboardState::~KeyboardState()
{
	Unload();
}

bool KeyboardState::IsKeyDown(VirtualKey key)
{
	return this->keys[key] == true;
}
bool KeyboardState::IsKeyUp(VirtualKey key)
{
	return this->keys[key] == false;
}

void KeyboardState::SaveKeyState(VirtualKey key, bool IsPressed)
{
	this->keys[key] = IsPressed;
}

void KeyboardState::ClearBuffer()
{
	for (auto k : this->keys)
	{    
		k.second = false; 
	}
}
void KeyboardState::Unload()
{
	this->keys.clear();
}


