/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
	Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : Game.h
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description :
*/

#pragma once

using namespace Microsoft::WRL;
using namespace Platform;

namespace AMP
{
	extern concurrency::accelerator_view  accViewObj;
}

ref class Game abstract
{
internal:
	//Constructor 
	Game(Windows::UI::Core::CoreWindow^ coreWindow);

private:
	bool COMPOSED_WITH_XAML;
	void Load();
	void CreateDevice();
	void CreateWindowSize();
	void HandleDeviceLost();

protected private:
	GraphicsDevice GDevice;
	ComPtr<IDXGISwapChain1> swapChain;
	Windows::UI::Xaml::Controls::SwapChainBackgroundPanel^ swapChainPanel;
	ComPtr<ID3D11RenderTargetView> renderTargetView;
	ComPtr<ID3D11DepthStencilView> depthStencilView;
	Platform::String^ defaultAcceleratorName;

	D3D_FEATURE_LEVEL featureLevel;
	Windows::Foundation::Size renderTargetSize;
	Windows::Foundation::Rect windowBounds;
	Agile<Windows::UI::Core::CoreWindow> coreWindow;

public:
	virtual void Initialize();
	virtual void Initialize(Windows::UI::Xaml::Controls::SwapChainBackgroundPanel^ swapChainPanel);
	virtual void WindowSizeChanged();
	virtual void Render();
};
