/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
	Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : Debugger.cpp
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description :
*/

#include "pch.h"
#include "..\Debugger.h"

Debugger::Debugger(Graphics2D G2D)
{
	this->_Fps = ref new Fps(G2D);
	this->_Cpu = ref new CPU();
}

void Debugger::Update(float TotalTime, float DeltaTime)
{
	this->totalTime = TotalTime;
	this->deltaTime = DeltaTime;

	this->_Fps->Update(DeltaTime);
}

void Debugger::ShowStatus(SpriteBatch^ spriteBatch, SpriteFont^ spriteFont, DirectX::XMFLOAT2* Position)
{
	const float YPlus = 20;

	spriteBatch->ShowString("Fps : " + this->_Fps->fps.ToString(), Position, this->_Fps->FpsColor, spriteFont, Matrix3x2F::Identity());
	Position->y += YPlus;

	spriteBatch->ShowString("Elapsed Time: " + this->deltaTime.ToString(), Position, spriteFont);
	Position->y += YPlus;

	spriteBatch->ShowString("Total Time: " + this->totalTime.ToString(), Position, spriteFont);
	Position->y += YPlus;

	//spriteBatch->ShowString("Cpu : " + this->_Cpu->Name, Position, spriteFont);
	//Position->y += YPlus;

	spriteBatch->ShowString("Cpu Core(s) : " + this->_Cpu->TotalCores.ToString(), Position, spriteFont);
	Position->y += YPlus;
}

