/*
	FOR GETTING MORE INFORMATION ABOUT THIS CODE PLEASE CHECK http://directx11-1-gameprogramming.azurewebsites.net/
	THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
	Copyright (c) Microsoft Corporation. All rights reserved

	File Name        : CPU.cpp
	Generated by     : Pooya Eimandar (http://Pooya-Eimandar.com/)
	File Description :
*/

#include "pch.h"
#include "..\CPU.h"
#include <collection.h>

using namespace Windows::Devices::Enumeration;

CPU::CPU():totalCores(0)
{
	this->totalCores = 0;
	auto filter = "System.Devices.InterfaceClassGuid:=\"" + GUID_DEVICE_PROCESSOR + "\"";

	Concurrency::task<DeviceInformationCollection^>(DeviceInformation::FindAllAsync(filter, nullptr))
		.then([this](DeviceInformationCollection^ interfaces)
	{
		std::for_each(begin(interfaces), end(interfaces), [this](DeviceInformation^ DeviceInfo)
		{
			this->totalCores++;
			if (this->name->IsEmpty())
			{
				this->name = DeviceInfo->Name;
			}
		});
	});
}


